### ISSUE TITLE
General Todo List

### ISSUE THREAD

**Issue by Hornwitser** [Hornwitser/YetiBridge#1]
## Important stuff that should be implemented
- [ ] Translation of formatting.
  - [ ] Define subset of markdown to use for formatting internally.
  - [ ] Translate to and from IRC formatting codes.
- [ ] A simple command line based python application for running a bridge based on this library.
- [ ] Documentation.
